{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "plugin-sentry",
    "version": "1.3.7_v820_beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-sentry-1.3.7_v820_beta4.jar",
          "url": "plugin-sentry-1.3.7_v820_beta4.jar",
          "size": 129711,
          "sha512": "739ef98f5d6838a5aca5a340439399a426533eb2c9b6ad464bd3d9d8c64dbc8297cd5d3285b3b77c70670daf72d4a3f235c85c952b65a0b917e74aa90f81f4c3",
          "sha256": "eaf1063287dbee3fe2eb7e143b10b24907fc2473144cee49c06e9fc519d89b2f",
          "sha1": "9885637b8f547df2295312f4b9f0c32da2986b82",
          "md5": "358a88743d3b76e4ee2b075128426487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "privacy-annotation",
          "version": {
            "requires": "1.3.7_v820_beta4"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.1.68.android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-sentry-1.3.7_v820_beta4.jar",
          "url": "plugin-sentry-1.3.7_v820_beta4.jar",
          "size": 129711,
          "sha512": "739ef98f5d6838a5aca5a340439399a426533eb2c9b6ad464bd3d9d8c64dbc8297cd5d3285b3b77c70670daf72d4a3f235c85c952b65a0b917e74aa90f81f4c3",
          "sha256": "eaf1063287dbee3fe2eb7e143b10b24907fc2473144cee49c06e9fc519d89b2f",
          "sha1": "9885637b8f547df2295312f4b9f0c32da2986b82",
          "md5": "358a88743d3b76e4ee2b075128426487"
        }
      ]
    }
  ]
}
