{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "privacy-annotation",
    "version": "1.3.7_v820_beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-annotation-1.3.7_v820_beta4.jar",
          "url": "privacy-annotation-1.3.7_v820_beta4.jar",
          "size": 3560,
          "sha512": "8412266ed1c0df8cd3373eff548bee0076c6f2a5cd412eb39720a097cc98fa38d01632dabe60475c08786c48481ac2a77382bf662927bac01a6e074052780fc3",
          "sha256": "6ac9d86349f02c577f20354b5035e7166e327efa92da5007ce607eadd21c1584",
          "sha1": "b52ca17b7cf69e93af841f8dc6018260a8855c8c",
          "md5": "1d9e98e21f3d1ea14f79b00b23b55e58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-annotation-1.3.7_v820_beta4.jar",
          "url": "privacy-annotation-1.3.7_v820_beta4.jar",
          "size": 3560,
          "sha512": "8412266ed1c0df8cd3373eff548bee0076c6f2a5cd412eb39720a097cc98fa38d01632dabe60475c08786c48481ac2a77382bf662927bac01a6e074052780fc3",
          "sha256": "6ac9d86349f02c577f20354b5035e7166e327efa92da5007ce607eadd21c1584",
          "sha1": "b52ca17b7cf69e93af841f8dc6018260a8855c8c",
          "md5": "1d9e98e21f3d1ea14f79b00b23b55e58"
        }
      ]
    }
  ]
}
