{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "privacy-replace",
    "version": "1.3.7_v820_beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-replace-1.3.7_v820_beta4.aar",
          "url": "privacy-replace-1.3.7_v820_beta4.aar",
          "size": 3698,
          "sha512": "a3f87968c8bd611059a82ce713f6572e6a36d9850972e8eab241d2747f39dd3c4419f1e693314ea8cf780918a055653141db15b0500ae54a5e8b0137de840012",
          "sha256": "795ff2a9ce327f21d7d23cca588c1c6f10d12b04e5e8cca83785d81c4c847ca7",
          "sha1": "a8e15c00aea4ce20b5da03dc595f8102389fbe01",
          "md5": "8944df9aa02df0dff41d92f29c8ff033"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "hook-sentry",
          "version": {
            "requires": "1.3.7_v820_beta4"
          }
        },
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "privacy-annotation",
          "version": {
            "requires": "1.3.7_v820_beta4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-replace-1.3.7_v820_beta4.aar",
          "url": "privacy-replace-1.3.7_v820_beta4.aar",
          "size": 3698,
          "sha512": "a3f87968c8bd611059a82ce713f6572e6a36d9850972e8eab241d2747f39dd3c4419f1e693314ea8cf780918a055653141db15b0500ae54a5e8b0137de840012",
          "sha256": "795ff2a9ce327f21d7d23cca588c1c6f10d12b04e5e8cca83785d81c4c847ca7",
          "sha1": "a8e15c00aea4ce20b5da03dc595f8102389fbe01",
          "md5": "8944df9aa02df0dff41d92f29c8ff033"
        }
      ]
    }
  ]
}
