{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "plugin-sentry",
    "version": "1.3.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-sentry-1.3.7.4.jar",
          "url": "plugin-sentry-1.3.7.4.jar",
          "size": 129711,
          "sha512": "120837211913f77309a56fd8503c5dcb77e6d74c4d64d432a0a892ebed28310ef2d349cd83cb327ee6421315a184688c098a618a59a3c122457d2236139a97c3",
          "sha256": "5ee017ae44a011ee1e3e39a144ab667e2460c8e2d51c9d7959dd0121ec51cb2f",
          "sha1": "414f0da3e7f67449c761fb9cc21bdb2bf163715d",
          "md5": "25db46e9ba4e5c12adc87cefccbb91c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "privacy-annotation",
          "version": {
            "requires": "1.3.7.4"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.1.68.android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-sentry-1.3.7.4.jar",
          "url": "plugin-sentry-1.3.7.4.jar",
          "size": 129711,
          "sha512": "120837211913f77309a56fd8503c5dcb77e6d74c4d64d432a0a892ebed28310ef2d349cd83cb327ee6421315a184688c098a618a59a3c122457d2236139a97c3",
          "sha256": "5ee017ae44a011ee1e3e39a144ab667e2460c8e2d51c9d7959dd0121ec51cb2f",
          "sha1": "414f0da3e7f67449c761fb9cc21bdb2bf163715d",
          "md5": "25db46e9ba4e5c12adc87cefccbb91c1"
        }
      ]
    }
  ]
}
