{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "privacy-proxy",
    "version": "1.3.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-proxy-1.3.7.4.aar",
          "url": "privacy-proxy-1.3.7.4.aar",
          "size": 76843,
          "sha512": "8b601769df596dee0bd75c6d7a139b624b9db9957a32b59a2da58111d3545160541521df176ac0c2ad108331224d185e7bacccfc2f390d348a84be8a201cc209",
          "sha256": "8f8be4fe0b3c45338a3a4310a071b50e1653fdf6e81ba3d8d60d2ceb8693c330",
          "sha1": "bba9d0f82233aae457902170aaa882b86b3dc313",
          "md5": "416095d2deabe66f2b7dea3ca5dbd662"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "2.0.19.android"
          }
        },
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "hook-sentry",
          "version": {
            "requires": "1.3.7.4"
          }
        },
        {
          "group": "com.github.yuanshuaiding.PrivacyGovern",
          "module": "privacy-annotation",
          "version": {
            "requires": "1.3.7.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-proxy-1.3.7.4.aar",
          "url": "privacy-proxy-1.3.7.4.aar",
          "size": 76843,
          "sha512": "8b601769df596dee0bd75c6d7a139b624b9db9957a32b59a2da58111d3545160541521df176ac0c2ad108331224d185e7bacccfc2f390d348a84be8a201cc209",
          "sha256": "8f8be4fe0b3c45338a3a4310a071b50e1653fdf6e81ba3d8d60d2ceb8693c330",
          "sha1": "bba9d0f82233aae457902170aaa882b86b3dc313",
          "md5": "416095d2deabe66f2b7dea3ca5dbd662"
        }
      ]
    }
  ]
}
