{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.yuanshuaiding.PrivacyGovern",
    "module": "privacy-annotation",
    "version": "1.3.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-annotation-1.3.7.4.jar",
          "url": "privacy-annotation-1.3.7.4.jar",
          "size": 3560,
          "sha512": "578a1056a0cfa2e9853259b4f55c70c99757e32b699ffebe9dbdece2b8d2db1cb995520e04470c09aeb2cbb3cc34fa0c695644c30cd8fb2b3f75f3af5403a9ec",
          "sha256": "cfba1fa4ba24deaee536467a54ebd35442b3f58123077d06410034542e196e54",
          "sha1": "f4ad50ca7eb10d023d4023c8105c8da219038f71",
          "md5": "1c6aa3012ac59f149bf25f7eeb229bd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacy-annotation-1.3.7.4.jar",
          "url": "privacy-annotation-1.3.7.4.jar",
          "size": 3560,
          "sha512": "578a1056a0cfa2e9853259b4f55c70c99757e32b699ffebe9dbdece2b8d2db1cb995520e04470c09aeb2cbb3cc34fa0c695644c30cd8fb2b3f75f3af5403a9ec",
          "sha256": "cfba1fa4ba24deaee536467a54ebd35442b3f58123077d06410034542e196e54",
          "sha1": "f4ad50ca7eb10d023d4023c8105c8da219038f71",
          "md5": "1c6aa3012ac59f149bf25f7eeb229bd1"
        }
      ]
    }
  ]
}
